import { REGION_BY_NAME } from "./worldLogic";

const DUNGEON_PRACTICE: Record<string, string> = {
  "Deku Tree": "oot-deku",
  "Dodongos Cavern": "oot-dc",
  "Jabu Jabus Belly": "oot-jabu",
  "Forest Temple": "oot-forest",
  "Fire Temple": "oot-fire",
  "Water Temple": "oot-water",
  "Shadow Temple": "oot-shadow",
  "Spirit Temple": "oot-spirit",
  "Bottom of the Well": "oot-well",
  "Ice Cavern": "oot-ice",
  "Gerudo Training Ground": "oot-gtg",
  "Ganons Castle": "oot-ganon",
};

const EXACT: Record<string, string> = {
  "Kokiri Forest": "oot-kokiri",
  "Deku Theater": "oot-deku-theater",
  "Lost Woods": "oot-lost-woods",
  "LW Beyond Mido": "oot-lost-woods",
  "LW Forest Exit": "oot-lost-woods",
  "LW Underwater Entrance": "oot-lost-woods",
  "LW Bridge": "oot-lost-woods-bridge",
  "LW Bridge From Forest": "oot-lost-woods-bridge",
  "GC Woods Warp": "oot-gc",
  "Sacred Forest Meadow": "oot-sfm",
  "SFM Entryway": "oot-sfm",
  "SFM Forest Temple Entrance Ledge": "oot-sfm",
  "Hyrule Field": "oot-field",
  "Lon Lon Ranch": "oot-llr",
  "Market": "oot-market",
  "Market Entrance": "oot-market",
  "Market Guard House": "oot-market",
  "Market Bazaar": "oot-market",
  "Market Potion Shop": "oot-market",
  "Market Bombchu Shop": "oot-market",
  "Market Treasure Chest Game": "oot-market",
  "Market Back Alley": "oot-market",
  "Man in Green House": "oot-market",
  "Temple of Time": "oot-tot",
  "Temple of Time Entrance": "oot-tot",
  "ToT Beyond Door of Time": "oot-tot",
  "Castle Grounds": "oot-castle",
  "Hyrule Castle Grounds": "oot-castle",
  "Hyrule Castle": "oot-castle",
  "HC Garden": "oot-castle",
  "HC Garden Skippable Locations": "oot-castle",
  "Ganons Castle Grounds": "oot-ganon-out",
  "Ganons Castle Ledge": "oot-ganon-out",
  "Castle Grounds From Ganons Castle": "oot-ganon-out",
  "OGC Great Fairy Fountain": "oot-ganon-out",
  "Kakariko Village": "oot-kak",
  "Kak Windmill": "oot-kak",
  "Graveyard": "oot-graveyard",
  "Graveyard Warp Pad Region": "oot-graveyard",
  "Death Mountain": "oot-dmt",
  "Death Mountain Summit": "oot-dmt",
  "Goron City": "oot-gc",
  "GC Darunias Chamber": "oot-gc",
  "GC Woods Warp": "oot-gc",
  "GC Shop": "oot-gc",
  "DMC Upper Nearby": "oot-dmc",
  "DMC Lower Nearby": "oot-dmc",
  "DMC Central Local": "oot-dmc",
  "DMC Lower Local": "oot-dmc",
  "DMC Upper Local": "oot-dmc",
  "DMC Distorted Room": "oot-dmc",
  "DMC Great Fairy Fountain": "oot-dmc",
  "Zora River": "oot-zr",
  "Zoras Domain": "oot-zd",
  "Zoras Domain Behind King Zora": "oot-zd",
  "Zoras Fountain": "oot-zf",
  "Lake Hylia": "oot-lh",
  "LH Fishing Hole": "oot-lh",
  "Water Temple Entryway": "oot-lh",
  "Gerudo Valley": "oot-gv",
  "GV Fortress Side": "oot-gv",
  "Gerudo Fortress": "oot-gf",
  "GF Entrances Behind Crates": "oot-gf",
  "GF Roof": "oot-gf",
  "GF Kitchen": "oot-gf",
  "Hideout 1 Torch Jail": "oot-gf",
  "Haunted Wasteland": "oot-wasteland",
  "Wasteland Near Fortress": "oot-wasteland",
  "Wasteland Near Colossus": "oot-wasteland",
  "Desert Colossus": "oot-colossus",
  "Colossus Great Fairy Fountain": "oot-colossus",
  "Queen Gohma Boss Room": "oot-deku",
  "King Dodongo Boss Room": "oot-dc",
  "Barinade Boss Room": "oot-jabu",
  "Phantom Ganon Boss Room": "oot-forest",
  "Volvagia Boss Room": "oot-fire",
  "Morpha Boss Room": "oot-water",
  "Bongo Bongo Boss Room": "oot-shadow",
  "Twinrova Boss Room": "oot-spirit",
  "Ganons Castle Tower": "oot-ganon",
  "Ganondorf Boss Room": "oot-ganon",
};

const PREFIX: [string, string][] = [
  ["KF ", "oot-kokiri"],
  ["LW ", "oot-lost-woods"],
  ["SFM ", "oot-sfm"],
  ["HF ", "oot-field"],
  ["LLR ", "oot-llr"],
  ["Kak ", "oot-kak"],
  ["Graveyard", "oot-graveyard"],
  ["DMT ", "oot-dmt"],
  ["Death Mountain", "oot-dmt"],
  ["GC ", "oot-gc"],
  ["DMC ", "oot-dmc"],
  ["ZR ", "oot-zr"],
  ["ZD ", "oot-zd"],
  ["Zoras Domain", "oot-zd"],
  ["ZF ", "oot-zf"],
  ["Zoras Fountain", "oot-zf"],
  ["LH ", "oot-lh"],
  ["Lake Hylia", "oot-lh"],
  ["GV ", "oot-gv"],
  ["Gerudo Valley", "oot-gv"],
  ["GF ", "oot-gf"],
  ["Hideout ", "oot-gf"],
  ["Gerudo Fortress", "oot-gf"],
  ["Wasteland", "oot-wasteland"],
  ["Haunted Wasteland", "oot-wasteland"],
  ["Colossus", "oot-colossus"],
  ["Desert Colossus", "oot-colossus"],
  ["Market", "oot-market"],
  ["HC ", "oot-castle"],
  ["Hyrule Castle", "oot-castle"],
  ["Castle Grounds", "oot-castle"],
  ["OGC ", "oot-ganon-out"],
  ["Ganons Castle Grounds", "oot-ganon-out"],
  ["ToT ", "oot-tot"],
  ["Temple of Time", "oot-tot"],
  ["Deku Tree", "oot-deku"],
  ["Dodongos Cavern", "oot-dc"],
  ["Jabu Jabus Belly", "oot-jabu"],
  ["Forest Temple", "oot-forest"],
  ["Fire Temple", "oot-fire"],
  ["Water Temple", "oot-water"],
  ["Shadow Temple", "oot-shadow"],
  ["Spirit Temple", "oot-spirit"],
  ["Child Spirit", "oot-spirit"],
  ["Adult Spirit", "oot-spirit"],
  ["Early Adult Spirit", "oot-spirit"],
  ["Bottom of the Well", "oot-well"],
  ["Ice Cavern", "oot-ice"],
  ["Gerudo Training Ground", "oot-gtg"],
  ["Ganons Castle", "oot-ganon"],
];

const SKIP = new Set([
  "Root",
  "Root Exits",
  "Child Spawn",
  "Adult Spawn",
  "Farores Wind Warp",
  "Prelude of Light Warp",
  "Minuet of Forest Warp",
  "Bolero of Fire Warp",
  "Serenade of Water Warp",
  "Nocturne of Shadow Warp",
  "Requiem of Spirit Warp",
]);

export function practiceIdFor(regionName: string): string | undefined {
  if (SKIP.has(regionName)) return undefined;
  const region = REGION_BY_NAME[regionName];
  if (region?.dungeon && DUNGEON_PRACTICE[region.dungeon]) return DUNGEON_PRACTICE[region.dungeon];
  if (EXACT[regionName]) return EXACT[regionName];
  for (const [prefix, id] of PREFIX) {
    if (regionName === prefix.trim() || regionName.startsWith(prefix)) return id;
  }
  return undefined;
}

export const PRACTICE_ENTRY: Record<string, string> = {
  "oot-kokiri": "Kokiri Forest",
  "oot-lost-woods": "Lost Woods",
  "oot-lost-woods-bridge": "LW Bridge From Forest",
  "oot-deku-theater": "Deku Theater",
  "oot-sfm": "Sacred Forest Meadow",
  "oot-field": "Hyrule Field",
  "oot-market": "Market",
  "oot-tot": "Temple of Time",
  "oot-castle": "Hyrule Castle Grounds",
  "oot-ganon-out": "Ganons Castle Grounds",
  "oot-llr": "Lon Lon Ranch",
  "oot-kak": "Kakariko Village",
  "oot-graveyard": "Graveyard",
  "oot-dmt": "Death Mountain",
  "oot-gc": "Goron City",
  "oot-dmc": "DMC Upper Nearby",
  "oot-zr": "Zora River",
  "oot-zd": "Zoras Domain",
  "oot-zf": "Zoras Fountain",
  "oot-lh": "Lake Hylia",
  "oot-gv": "Gerudo Valley",
  "oot-gf": "Gerudo Fortress",
  "oot-wasteland": "Wasteland Near Fortress",
  "oot-colossus": "Desert Colossus",
  "oot-deku": "Deku Tree Lobby",
  "oot-dc": "Dodongos Cavern Beginning",
  "oot-jabu": "Jabu Jabus Belly Beginning",
  "oot-forest": "Forest Temple Lobby",
  "oot-fire": "Fire Temple Lower",
  "oot-water": "Water Temple Lobby",
  "oot-shadow": "Shadow Temple Entryway",
  "oot-spirit": "Spirit Temple Lobby",
  "oot-well": "Bottom of the Well",
  "oot-ice": "Ice Cavern Beginning",
  "oot-gtg": "Gerudo Training Ground Lobby",
  "oot-ganon": "Ganons Castle Lobby",
};

export function entryRegion(practiceId: string): string | undefined {
  return PRACTICE_ENTRY[practiceId];
}
